influx:
  url: "http://10.10.3.3:8086"
  token: ${INFLUX_TOKEN}
  org: "homelab"
  bucket: "networking"

iperf:
  name: ${hostname}
  interval: 30
  servers:
    - name: storm 
      address: 10.10.1.1
      duration: 2
    - name: nemo
      address: 10.10.2.1
      port: 5201
      duration: 2
    - name: zoro 
      address: 10.10.3.1
      port: 5201
      duration: 2
    - name: omv 
      address: 10.10.4.1
      port: 5201
      duration: 2
    - name: goku
      address: 10.10.5.1
      port: 5201
      duration: 2